- .github/workflows/deploy-to-production.yml
- .github/workflows/run-tests.yml
- .platform/hooks/postdeploy/10_env_set.sh
- docker-compose.yml
Related Task: https://whatshafiz.atlassian.net/browse/WH-15
> feature/WH-15 AWS ve domain kurulumu

- src/app/Http/Controllers/RegulationController.php
- src/app/Models/Regulation.php
- src/app/Policies/RegulationPolicy.php
- src/app/Providers/AuthServiceProvider.php
- src/database/migrations/2022_10_29_145941_create_regulations_table.php
- src/database/seeders/DatabaseSeeder.php
- src/database/seeders/RegulationSeeder.php
- src/database/seeders/RolesPermissionsSeeder.php
- src/routes/api.php
- src/tests/Feature/Regulation/RegulationTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-8
> feature/WH-8 Regulations CRUD actions

- docs/README.md
- docs/whatshafiz.postman_collection.json
Related task: https://whatshafiz.atlassian.net/browse/WH-27
> feature/WH-27 Postman Collection oluşturma

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/PeriodController.php
- src/app/Http/Controllers/WhatsappGroupController.php
- src/app/Models/BaseModel.php
- src/app/Models/User.php
- src/app/Models/WhatsappGroup.php
- src/app/Models/WhatsappGroupUser.php
- src/app/Policies/WhatsappGroupPolicy.php
- src/app/Providers/AuthServiceProvider.php
- src/database/factories/PeriodFactory.php
- src/database/factories/WhatsappGroupFactory.php
- src/database/factories/WhatsappGroupUserFactory.php
- src/database/migrations/2022_11_28_130706_create_whatsapp_groups_table.php
- src/database/migrations/2022_11_29_094543_create_whatsapp_group_users_table.php
- src/database/seeders/DatabaseSeeder.php
- src/database/seeders/PeriodSeeder.php
- src/database/seeders/RolesPermissionsSeeder.php
- src/database/seeders/WhatsappGroupSeeder.php
- src/routes/api.php
- src/tests/Feature/PeriodTest.php
- src/tests/Feature/WhatsappGroupTest.php
Related Task:  https://whatshafiz.atlassian.net/browse/WH-13
> feature/WH-13  Whatsapp Grup and Users CRUD

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/SettingController.php
- src/app/Models/Setting.php
- src/database/factories/SettingFactory.php
- src/database/migrations/2022_12_13_051836_create_settings_table.php
- src/database/seeders/DatabaseSeeder.php
- src/database/seeders/SettingSeeder.php
- src/database/seeders/UserSeeder.php
- src/routes/api.php
- src/tests/Feature/SettingTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-30
> feature/WH-30 Settings CRUD

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/UserController.php
- src/app/Models/Course.php
- src/app/Models/User.php
- src/app/Models/UserCourse.php
- src/database/factories/CourseFactory.php
- src/database/factories/UserCourseFactory.php
- src/database/migrations/2022_12_18_151744_create_user_course_table.php
- src/routes/api.php
- src/tests/Feature/CourseTest.php
- src/tests/Feature/ProfileTest.php
Related task: https://whatshafiz.atlassian.net/browse/WH-28
> feature/WH-28 Whatsenglish ve Whatsarapp için kullanılacak başvuru formu

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/UserController.php
- src/app/Models/PasswordReset.php
- src/app/Models/User.php
- src/composer.json
- src/composer.lock
- src/database/migrations/2022_12_20_143224_convert_email_to_phone_on_password_resets_table.php
- src/routes/api.php
- src/tests/Feature/LoginTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-31
> feature/WH-31 Forgot password api

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/UserController.php
- src/app/Http/Controllers/WhatsappGroupController.php
- src/app/Models/Course.php
- src/app/Models/WhatsappGroup.php
- src/database/data/countries.json
- src/database/factories/CourseFactory.php
- src/database/seeders/RolesPermissionsSeeder.php
- src/tests/Feature/CourseTest.php
- src/tests/Feature/ProfileTest.php
- src/tests/Feature/WhatsappGroupTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-36
> feature/WH-36 28.12.2022 toplantı sonrası belirlenen ufak düzeltmeler

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/RegulationController.php
- src/database/migrations/2023_01_14_085636_add_summary_column_to_regulations_table.php
- src/database/seeders/RegulationSeeder.php
- src/tests/Feature/RegulationTest.php
Related task: https://whatshafiz.atlassian.net/browse/WH-43
> feature/WH-43 Summary column added to regulations table

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/UserController.php
- src/app/Models/UserCourse.php
- src/routes/api.php
- src/tests/Feature/ProfileTest.php
Related task: https://whatshafiz.atlassian.net/browse/WH-54
> feature/WH-54 GET profile/courses  servisinin yazılması 

- src/app/Http/Controllers/SettingController.php
- src/routes/api.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-77
> feature/WH-77 System Settings front end fixes

- src/app/Http/Controllers/CountryController.php
- src/app/Http/Controllers/RoleController.php
- src/app/Http/Controllers/SettingController.php
- src/app/Models/City.php
- src/app/Models/Country.php
- src/app/Policies/CountryPolicy.php
- src/app/Providers/AuthServiceProvider.php
- src/database/seeders/RolesPermissionsSeeder.php
- src/routes/api.php
- src/tests/Feature/CountryTest.php
[Ne](https://github.com/whatshafiz/whatshafiz-frontend/compare/feature/WH-68?expand=1)
> feature/WH-68   Ülke Şehir CRUD

- src/app/Http/Controllers/QuranQuestionController.php
- src/database/factories/QuranQuestionFactory.php
- src/tests/Feature/QuranQuestionTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-85
> feature/WH-85 Meal Soruları CRUD işlemleri

- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/WhatsappGroupController.php
- src/routes/api.php
- src/tests/Feature/CourseTest.php
- src/tests/Feature/WhatsappGroupTest.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-72
> feature/WH-72 whatsappgroups CRUD

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/ComplaintController.php
- src/app/Models/Complaint.php
- src/database/factories/ComplaintFactory.php
- src/database/migrations/2023_03_05_132824_create_complaints_table.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-73
> feature/WH-73 şikayetler CRUD

- src/app/Http/Controllers/CommentController.php
- src/app/Http/Controllers/ComplaintController.php
- src/database/seeders/RolesPermissionsSeeder.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-74
> feature/WH-74 yorumlar CRUD

- src/app/Http/Controllers/CourseController.php
- src/database/factories/CourseFactory.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-71
> feature/WH-71 kurslar CRUD

- src/app/Http/Controllers/CommentController.php
- src/app/Http/Controllers/ComplaintController.php
- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/WhatsappGroupController.php
- src/app/Models/Course.php
- src/routes/api.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-90
> feature/WH-90 MY Index Sayfaları

- src/app/Http/Controllers/UserController.php
- src/app/Models/User.php
- src/routes/api.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-89
> feature/WH-89 Kullanıcılar Index View

- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/UserController.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-92
> feature/WH-92 Kurs ve Whatsapp Grubu Kullanıcı listeleri

- src/app/Http/Controllers/RoleController.php
- src/app/Http/Controllers/UserController.php
- src/database/factories/UserFactory.php
- src/routes/api.php
Related Task: https://whatshafiz.atlassian.net/browse/WH-95
> feature/WH-95 User role assign

- docs/whatshafiz.postman_collection.json
- src/app/Http/Controllers/WhatsappMessengerNumberController.php
- src/app/Models/WhatsappMessengerNumber.php
- src/app/Providers/AuthServiceProvider.php
- src/app/Traits/S3Trait.php
- src/composer.json
- src/composer.lock
- src/database/factories/WhatsappMessengerNumberFactory.php
- src/database/migrations/2023_05_11_170954_create_whatsapp_messenger_numbers_table.php
- src/database/seeders/DatabaseSeeder.php
- src/database/seeders/WhatsappMessengerNumberSeeder.php
- src/routes/api.php
- src/tests/Feature/WhatsappMessengerNumberTest.php
feature/WH-60 WhatsappMessenger Yönetim Sayfası
> feature/WH-60 WhatsappMessenger Yönetim Sayfası

- src/app/Http/Controllers/CourseController.php
- src/app/Http/Controllers/UserController.php
- src/app/Http/Controllers/WhatsappGroupController.php
- src/app/Jobs/CourseWhatsappGroupsOrganizer.php
- src/app/Jobs/WhatshafizCourseWhatsappGroupsOrganizer.php
- src/app/Models/Course.php
- src/app/Models/User.php
- src/database/factories/UserFactory.php
- src/database/factories/WhatsappGroupUserFactory.php
- src/database/migrations/2024_02_15_152735_add_course_id_column_to_whatsapp_group_users_table.php
- src/database/migrations/2024_02_16_142122_add_whatsapp_group_id_column_to_user_course_table.php
- src/database/seeders/ProductionLoadTestSeeder.php
- src/tests/BaseFeatureTest.php
- src/tests/Feature/CourseTest.php
- src/tests/Feature/Jobs/CourseWhatsappGroupsOrganizerTest.php
- src/tests/Feature/Jobs/WhatshafizCourseWhatsappGroupsOrganizerTest.php
- src/tests/Feature/LoginTest.php
- src/tests/Feature/ProfileTest.php
- src/tests/Feature/RegisterTest.php
- src/tests/Feature/WhatsappGroupTest.php
Whatsapp duyuru kanalı eklendi, yeni üyeler otomatik gruba atanmıyor. Bu kanalı takip etmeleri isteniyor.
Kullanıcılar daha sonradan gruplara ortak özelliklere göre atanıyor.
> ocak toplanti
